#ifndef NODE_A_CONFIG_H
#define NODE_A_CONFIG_H

#define NODE_A_DEFAULT_WIFI_SSID "bindsoft"
#define NODE_A_DEFAULT_WIFI_PASSWORD "bindsoft24"
#define NODE_A_DEFAULT_MQTT_SERVER "163.152.213.111"

#define NODE_A_DEFAULT_MQTT_USERNAME ""
#define NODE_A_DEFAULT_MQTT_PASSWORD ""

#define NODE_A_DEFAULT_MQTT_PORT 1883
#define NODE_A_DEFAULT_MQTT_KEEP_ALIVE_S 60
#define NODE_A_DEFAULT_MQTT_QOS 1

#endif
